version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sample_db
      MYSQL_USER: usr
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=1234 --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
